---
# This is a signed yaml file, run "drone sign levitatebio/configstore --save" after any changes
name: default
kind: pipeline
type: kubernetes
node_selector:
  CPUs: 8

steps:
  - name: Run tests
    image: golang
    commands:
      - go test

---
kind: signature
hmac: b74fdd36f8d75e8c473e9f4f0711c1483fa3f8e0cfd1fff83884e78eb67a3216

...
